version: '3.8'

services:
  app:
    build: .
    container_name: my-app
    ports:
      - "8080:8080" # Frontend
      - "3000:3000" # Backend
    volumes:
      - ./frontend-app:/frontend-app
      - ./backend:/backend
    environment:
      - NODE_ENV=production
    command: bash -c "npm run build --prefix /frontend-app && npm start --prefix /backend"
