name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: latest

    - name: Build the Docker image using Docker Compose
      run: |
        sudo docker-compose -f docker-compose.yml build

    - name: Save Docker image to a tar file (skip upload)
      run: |
        IMAGE_TAG=my-image-name:$(date +%s)
        sudo docker-compose -f docker-compose.yml build
        sudo docker save $IMAGE_TAG -o my-image-name.tar
